### ISSUE TITLE
Missing env variable

### ISSUE THREAD

**Issue by abea** [ThatConference/that-website#118]
Running `now dev` with now installed globally now returns the error:

```
> Now CLI 16.6.2 dev (beta) — https://zeit.co/feedback/dev
> Error! Env var "SENTRY_DSN" is not defined in `.env.build` file
Read more: https://err.sh/now/missing-env-file
```

In the `.env` sample files that variable is empty.

**Comment by GregLevenhagen** [comment]
Have you tried putting the `SENTRY_DSN=` without a value into your `.env` file? It should work without a value, but it does require the key.

**Comment by abea** [comment]
I don't know if this was from a build process or the initial `git clone`, but my `.env` file has:

```
API_URL=http://localhost:8000
SENTRY_DSN=
```

So I guess I'm missing the key? I don't recall seeing mention of that. And `now dev` did work fine for me a couple of weeks ago.

**Comment by csell5** [comment]
You now need two .env files `.env` and `.env.build`. This was a recommendation from the now team.

Both need an empty `SENTRY_DSN=`.

If you look at now.json in the root, it details all the env settings for env and env.build you will need. the new auth stuff just make empty.
