### ISSUE TITLE
favicon missing on markdown pages

### ISSUE THREAD

**Issue by saragibby** [ThatConference/that-website#122]
Rendered markdown pages appear to be missing the favicon.

Examples:
https://www.thatconference.com/blog/that-2019-holiday-buying-guide
https://www.thatconference.com/wi/copyright

Looks like we should include a " - THAT Conference" suffix in the page title. Also, we have a description for each markdown page we might be able to do a better job with the meta to include that in the page details.

**Comment by zaudtke** [comment]
@saragibby I was looking at this earlier.  I found the fix the missing Favicon, but had to wait for the Open PR that is now complete.

To clarify this one:

1. Do you want a " - THAT Conference" suffix added to the markdown pages as part of this?
2. Is there any more detail on the desire for better meta data?

I'll try and get to the icon and #1 this weekend at the latest.

**Comment by saragibby** [comment]
That is awesome @zaudtke! Thanks so much for picking this up and diving in!

1. Yes, adding " - THAT Conference" to the markdown pages title would be great

2. I haven't put much thought into beyond our SEO on those pages is weak-sauce. My original thought was adding the description would help some, but I am sure there is more we can do. If you have thoughts/suggestions/ideas I'd love to hear them!

**Comment by zaudtke** [comment]
@saragibby easy thing first :)

1.  I have no ideas on the SEO stuff, as all my projects are locked down behind logins.  I have no SEO Experience

2.  After adding the "- THAT Conference" suffix, I'm not sure it's what you want.  The `Title` metadata gets added to the Browser Tab, but also gets added to the Content title on the page, so for a blog or the privacy policy you would get as seen in the attachments here.  (Assumes you meant all MD pages, and not just blog)
![Screen Shot 2019-12-27 at 3 38 00 PM](https://user-images.githubusercontent.com/1631560/71531963-2bfbac80-28bf-11ea-900d-2c7d141b809d.png)
![Screen Shot 2019-12-27 at 3 38 40 PM](https://user-images.githubusercontent.com/1631560/71531964-2bfbac80-28bf-11ea-80c3-14ac30ceaea8.png)

**Comment by zaudtke** [comment]
It looks like if the desired result is having " - THAT Conference" suffix in the Tab but not the content, a quick edit to `[post].js` and [markdown].s` would solve it, without needing to add the suffix to each markdown page.

**Comment by saragibby** [comment]
You got it, in the tab heading but not in the content within the page. If you can get that and the favicon working that would be awesome! 

I just looked a bit at the SEO pieces I mentioned and have some other ideas how to get that beefed up, but will be a more involved effort. I can lay that out separately as another issue so we can pull in the blog post deets into the meta data.

**Comment by saragibby** [comment]
Closing as completed in #190 🌟
