### ISSUE TITLE
LinkButton's need hover style

### ISSUE THREAD

**Issue by saragibby** [ThatConference/that-website#134]
The `LinkButton` component is used is all locations to represent the links you see with a border and text in the middle. These links are designed to have a style on hover that is not yet implemented:

![image](https://user-images.githubusercontent.com/82035/70877465-8d508100-1f8b-11ea-88b6-fbc567880cce.png)
![image](https://user-images.githubusercontent.com/82035/70877470-93466200-1f8b-11ea-9cd9-294a9f866de4.png)

All the colors are contained in `baseTheme`. 

`LinkButton` assumes a blue outline and text, but allows for props to be passed in to change the color for additional scenarios. Hover styles will need to work in all scenarios.

**Comment by zaudtke** [comment]
@saragibby Let me know if I missed anything, or you would like it done differently.

**Comment by zaudtke** [comment]
@kburnell @saragibby I think this can be closed now that PR was completed.

**Comment by saragibby** [comment]
Closing as completed with #161 
Thanks again @zaudtke for tackling this one!
