### ISSUE TITLE
Center Header Elements on Mobile

### ISSUE THREAD

**Issue by csell5** [ThatConference/that-website#135]
![image](https://user-images.githubusercontent.com/772569/70912881-7f761c80-1fda-11ea-88c0-8e55e793f4f8.png)

**Comment by tsidel** [comment]
@csell5 - is this still an issue? When I load the mobile version - the mobile nav shows up on the right, so it'd be hard to center this with the nav in place.

(There are some other things to look into though based on my mobile  screenshot - looks like the ContentSection__Container in the header has different padding settings than the ContentSection__Container in the Page__Inner div) But I wanted to check on the centering issue first.

<img width="317" alt="Screen Shot 2019-12-31 at 6 44 51 PM" src="https://user-images.githubusercontent.com/194128/71636954-f841bf00-2bfd-11ea-90cd-0e1a6b2bf164.png">

**Comment by saragibby** [comment]
There have been some slight adjustments to the design from the original mocks, but here is the top area of the original mobile landing design:
![image](https://user-images.githubusercontent.com/82035/71682412-a617af80-2d5d-11ea-9f34-60da7d7203b3.png)

We could keep with the centering theme, or we could make the buttons full width and left align the text headings like in the original design. I'd be curious to see how it would look more to the original design. 

Also, odd that the mobile menu is not there on @csell5's screen shot. 🤔

Add agree with you @tsidel, there is a padding difference overall that should be consistent.

**Comment by tsidel** [comment]
I like the idea of keeping with the original design. Is it alright if I change up the CSS to match that?

**Comment by tsidel** [comment]
I've started working on this. This might also fix Issue #308

**Comment by saragibby** [comment]
Closing, fixed with #318
