### ISSUE TITLE
Notification should link ...

### ISSUE THREAD

**Issue by csell5** [ThatConference/that-website#139]
![image](https://user-images.githubusercontent.com/772569/70945594-27133f00-201b-11ea-8a7b-41f6923e9ea3.png)

In this case.. That notification should link to the call for speakers home page. it's currently not a link.

**Comment by saragibby** [comment]
This page is not built yet. As soon as we get the page live we will link this up.

**Comment by saragibby** [comment]
Implemented as part of #179
