### ISSUE TITLE
Site images are not being cached in browser

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#149]
Looking at the network tab in browser tools it appears none of the site images are being cached locally, they are being downloaded with each request. It would be beneficial to the end user, and bandwidth usage to have these cached. This has been noticed on all pages reviewed. 

To reproduce: 
Open browser and browser tools
Navigate to https://www.thatconference.com
Click on a partners
Click back to home page
Reload a page

What you see:
After an initial page load Image downloads have status 200 

What is expected:
After an initial page load locally cached items, like images, should have a result of 304 (not modified).

**Comment by mcookWI** [comment]
Trying to duplicate this and I'm getting 304 status on Safari, Firefox and Chrome. Has this been corrected?

**Comment by brettski** [comment]
@mcookWI can you include a screenshot of what you are seeing?

**Comment by brettski** [comment]
No longer able to repro
