### ISSUE TITLE
Hero image is out of place

### ISSUE THREAD

**Issue by csell5** [ThatConference/that-website#150]
https://www.thatconference.com/wi/partners

![image](https://user-images.githubusercontent.com/772569/71254943-20721980-22f2-11ea-9fa7-2f763940f9d1.png)

**Comment by tsidel** [comment]
@csell5 - I've not been able to reproduce this in the browsers I've tested. Which browser and OS is your screenshot from?

I've tested in the latest versions of Firefox, Chrome, Safari on a Mac desktop. I hopped over to browserstack.com and looked at Edge 18 and 17,  and IE 11 (which in IE 11, the robot is on the right, and text on the left, but it degrades nicely).

**Comment by csell5** [comment]
You know, I think it got fixed when I rearranged how we create the apollo client.
