### ISSUE TITLE
Add Flickr to social icons

### ISSUE THREAD

**Issue by saragibby** [ThatConference/that-website#196]
Currently we are missing the Flickr social link in our lineup of socials:
![image](https://user-images.githubusercontent.com/82035/71703852-fb2ae400-2da4-11ea-981a-1f69a803467e.png)

To get this added there are a couple things that need to be done:
1. We currently don't have an svg set for Flickr in `svgs.js`. Need to get the Flickr logo as an svg and add it into this file so that it can be rendered. _Note: svg icons are currently set to render array of path values, not shapes. Flickr being 2 circle may not out of the gate fit this pattern._

2. Add Flickr to `SOCIALS` array within `SocialLinks.js` (https://www.flickr.com/photos/thatconference/)

**Comment by tsidel** [comment]
I'm going to look into this
