### ISSUE TITLE
HTTP401 Denied Accessing https://www.thatconference.com/api/me In Edge

### ISSUE THREAD

**Issue by tparikka** [ThatConference/that-website#201]
## Expected Behavior
Console errors, API permission errors should not occur when browsing the site on supported browsers.

## Current Behavior
The following error occurs when browsing to https://www.thatconference.com/api/me on Microsoft Edge in Windows 10 Pro:

![image](https://user-images.githubusercontent.com/7715790/71730527-0b27df80-2e08-11ea-8812-733914269589.png)

## Possible Solution
I am not familiar enough with the site code to know what call is being made that is being rejected.

## Steps to Reproduce
1. Navigate to https://www.thatconference.com/wi in Windows Edge on Win10 Pro.

**Comment by mcookWI** [comment]
@tparikka Confirming - you are seeing this error when going to the main /wi page? No additional steps are taken?

**Comment by tparikka** [comment]
@mcookWI At the time the issue was filed, that was the correct step. However, as of the latest release of the site that error no longer occurs.
