### ISSUE TITLE
Tidio-Chat box makes social icons unclickable

### ISSUE THREAD

**Issue by tsidel** [ThatConference/that-website#208]
The overlay of the Tidio Chat box covers up the social icons, and you can't click on them to access the social media links

<img width="627" alt="Screen Shot 2020-01-04 at 11 17 39 PM" src="https://user-images.githubusercontent.com/194128/71775569-8690aa80-2f48-11ea-8f35-9a6c4af43c3a.png">

The screenshot shows the coverage of the iframe, and anything beneath the blue box is not clickable.

We could address this with some z-index, but, if we do that we just reverse the issue.  Social Icons might render the Tidio Chat box unclickable. 

I'm thinking if we could have it be sticky to the bottom of the browser window viewport until you get to the top of the footer, then once the footer is in view the chatbot stops scrolling, and you then have access to the footer content.

**Comment by mcookWI** [comment]
Tidio-Chat has been moved to the lower left side of the footer and is no longer blocking the social icons.

**Comment by tsidel** [comment]
That's the most simple solution :D
