### ISSUE TITLE
Using become a counselor link not logged creates login again

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#221]
## Issue:
When you already have a site profile, are NOT logged in, and go through the "Become a Counselor" link, you are brought back to create a profile without any of your profile data loaded. It looks to only have Auth0 data. 

## Steps to reproduce:
1. Ensure you are not logged in
1. Click "Learn More" in the banner
1. Click "Become a Counselor" button
1. Click "Get Started" button
1. > You are redirected to login
1. Login with your previous established account

## Result
- You are directed to page > `/member/create` with no previously filled in profile data populated
 
## Desired Result
- With a complete profile, directed to the session submission page
- or if create page is required programmatically, have the current profile data populated.

## Side affect
Though it seems no data is lost, I was asked to accept the Counselor Agreement again

**Comment by brettski** [comment]
FYI. @csell5 is working on a 'required auth' hook to handle these conditions.

**Comment by saragibby** [comment]
@brettski did we get this resolved earlier or is this still an issue?

**Comment by brettski** [comment]
This has been corrected.
