### ISSUE TITLE
Session Submit: Required fields update

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#230]
## Update the requirement of the following fields in the Session Submit pages:

Required (any type of session):
- Key Take-aways (additional info page)
- Why are you the best person to give this talk?

Required for Workshops (not required for regular sessions):
- Prerequisites or previous Experience (Additional info page)
- Agenda (Additional Info page)

Not required:
- What else should we know?

@kburnell @saragibby :  
Please note: am not sure on our requirements for Keynote submissions

**Comment by saragibby** [comment]
fixed in #268

**Comment by brettski** [comment]
looks good
