### ISSUE TITLE
Create Profile: Missing BIO throws site error

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#233]
## Issue
While creating a new profile, if the BIO is misising the site blows up with a write document error

## Steps to reproduce
1. Login as a new user or with a user who has not started to fill in there profile
1. Click link to create profile (banner or user dropdown)
1. On the first page, CONTCT INFO:
    1. Add Profile Slug you KNOW DOESN'T EXIST
    1. Check all: Agree to **Code of Conduct**, **Terms of Servicce**, and **over 13**
1. Click Continue
1. ONLINE PRESENCE page, leave all blank, click "Continue"
1. BIO page, leave blank and click "Continue"

### What happens 
error thrown
```
Error: Network error: Response not successful: Received status code 400
onError
./pages/member/create.js:99
   96 |   },
   97 |   onError: updateError => {
   98 |     dlog('Error updating member %o', updateError);
>  99 |     throw new Error(updateError);
      | ^  100 |   },
  101 | });
  102 | 
View compiled
▼ 2 stack frames were expanded.
MutationData.push../node_modules/@apollo/react-hooks/lib/react-hooks.esm.js.MutationData.onMutationError
./node_modules/@apollo/react-hooks/lib/react-hooks.esm.js:491
(anonymous function)
./node_modules/@apollo/react-hooks/lib/react-hooks.esm.js:419
▲ 2 stack frames were expanded.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
```

### What should happen
UI prompts user to enter required field BIO

**Comment by saragibby** [comment]
This is on the member side, so switching owner over to me.

**Comment by brettski** [comment]
#261 is related to this

form experience with empty bio

**Comment by saragibby** [comment]
fixed in #266

**Comment by brettski** [comment]
@saragibby a shortlist item.

On the Edit Profile page, I am able to clear out my bio and submit it empty. I now have no bio in my profile.

**Comment by saragibby** [comment]
Is this still a blocker for launch?

**Comment by brettski** [comment]
Closing this, we have other issue open for validation on edit page
