### ISSUE TITLE
Create Profile: Duplicate 'Profile Slug' not caught/handled

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#235]
## Issue
As a new user I am asked to add a username. If that username matches one already in use, the page continues. An error is thrown at the last page of setting up profile that the response is not successful.

## Steps to reproduce
1. Login as a new user or with a user who has not started to fill in their profile
1. On the first page, CONTCT INFO, enter a value for **Profile Slug** which you know to already be in use. E.g. `brettski-tc`
1. Fill in other required fields (check boxes), click Continue
1. ONLINE PRESENCE page, click Continue
1. BIO, add sufficient length bio, click Continue

### What happens
Site errors with error message below

### What should happen
The user needs to be prompted/warned their entered **Profile Slug** is already in use

Error  
```
Error: GraphQL error: profile slug is taken
onError
./pages/member/create.js:99
   96 |   },
   97 |   onError: updateError => {
   98 |     dlog('Error updating member %o', updateError);
>  99 |     throw new Error(updateError);
      | ^  100 |   },
  101 | });
  102 | 
View compiled
▼ 2 stack frames were expanded.
MutationData.push../node_modules/@apollo/react-hooks/lib/react-hooks.esm.js.MutationData.onMutationError
./node_modules/@apollo/react-hooks/lib/react-hooks.esm.js:491
(anonymous function)
./node_modules/@apollo/react-hooks/lib/react-hooks.esm.js:419
▲ 2 stack frames were expanded.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.```

**Comment by saragibby** [comment]
On profile, switching owner to me.

**Comment by saragibby** [comment]
Fixed in https://github.com/ThatConference/that-website/pull/253

**Comment by brettski** [comment]
Looks good
