### ISSUE TITLE
Profile should not require first and last names to be at least 3 characters

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#236]
When creating a profile, the page indicates that the first and last name fields must be at least 3 characters long. There are valid first and last names that may only be 2 characters (ex: Jo, Mo, Wu, Su, etc...).

Individuals with first and last names less than 3 characters cannot complete their profile and move through the submission process.

(/member/create)

<img width="1129" alt="Screen Shot 2020-01-07 at 1 58 45 PM" src="https://user-images.githubusercontent.com/5367626/71925350-764e1a80-3156-11ea-8972-88078a2b6ede.png">

**Comment by saragibby** [comment]
on profile, changing owner over to me

**Comment by saragibby** [comment]
fixed #268

**Comment by brettski** [comment]
Works as expected
