### ISSUE TITLE
/member/create - 'Profile Slug' field - can we add a description of what that is?

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#238]
It is possible that someone creating a member profile may not know what a 'Profile Slug' is - I didn't - and actually had to look it up.

This is an enhancement request to add a description under that field, or maybe a question mark a user can hover over for additional information.

**Comment by saragibby** [comment]
@mcookWI added some help text to this that went out this morning. When you can a review on that would be great!

**Comment by mcookWI** [comment]
Help text has been added under the Profile Slug text box:

<img width="392" alt="Screen Shot 2020-01-15 at 3 15 10 PM" src="https://user-images.githubusercontent.com/5367626/72472274-e1789c00-37a9-11ea-98e9-1743f790d3ac.png">
