### ISSUE TITLE
Hovering over 'Ticket Options' or 'Sponsor Us' - improper text color

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#24]
When you hover over 'Ticket Options' or 'Sponsor Us', the improper text color is displayed and you are unable to read the link.

<img width="614" alt="Screen Shot 2019-10-26 at 11 46 53 PM" src="https://user-images.githubusercontent.com/5367626/67629848-fc8edc00-f84a-11e9-921e-074defe3e730.png">

**Comment by saragibby** [comment]
@mcookWI @astralbodies did this get fixed with the updates this morning?

**Comment by astralbodies** [comment]
Yup this is fixed. Closing now.
