### ISSUE TITLE
/member/create - Entering any data in 'Slack Member ID' throws an error on Continue

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#240]
Whenever there is any data entered into the 'Slack Member ID' field on the member profile screen, an error is thrown when the user clicks 'Continue'. The console error I am seeing from the call to api.that.tech is attached.

[SlackFieldError.pdf](https://github.com/ThatConference/that-website/files/4032639/SlackFieldError.pdf)

**Comment by saragibby** [comment]
This is on the profile side so assigning over to me.

**Comment by brettski** [comment]
This is working as expected. Verified data stored

**Comment by brettski** [comment]
Slack user value does not populate in the form when editing a profile. 

You fix this from here or want a new ticket @saragibby ?

**Comment by saragibby** [comment]
on it

**Comment by saragibby** [comment]
edit fixed in #266

**Comment by brettski** [comment]
Looks good
