### ISSUE TITLE
Session Submission pages - 'Valid URL Required' error showing on valid URLs

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#242]
On any of the session submission pages, the URL fields are showing an error of 'Valid URL Required', even when a valid URL is being entered. 

Specifically, URLs entered as https, those with hyphens, or without www. are appearing with this error. However, if you click on 'Continue', you are still able to move through the process. If you go back to a previous page that showed the URL error, it no longer appears.

Steps to create the error:

1. Go to /wi/session/submit and select any valid options
2. Click 'Continue' to proceed to the Session Details page
3. Enter any data in requested fields
4. On 'Supporting Links/Related Resources', enter a URL starting with https, one that contains hyphens, or anything without www., such as http://valid-url.com and you will see the "Valid URL Required" error. This error should not come up with these entries, as they are valid URLs.

<img width="1037" alt="ValidURL1" src="https://user-images.githubusercontent.com/5367626/71941472-757dae80-317f-11ea-9ed5-63fe4a1879d2.png">
<img width="1037" alt="ValidURL2" src="https://user-images.githubusercontent.com/5367626/71941473-757dae80-317f-11ea-85da-d67132e61f27.png">

**Comment by mcookWI** [comment]
I now realize I am unable to get the + button to appear on an invalid URL. While the user can get past the screen with one 'invalid URL', they are unable to add additional ones if needed.

**Comment by brettski** [comment]
Corrected with pr #277

**Comment by brettski** [comment]
@mcookWI Please test

**Comment by mcookWI** [comment]
URLs are now acting as they should on the session submission page. Users will need to continue including http:// or https://.

**Comment by mcookWI** [comment]
@saragibby @brettski I'm okay with users having to enter the http:// or https:// - how about the two of you?

**Comment by brettski** [comment]
Yes, I feel that is required. I consider this issue closed
