### ISSUE TITLE
/wi/session/submit/details - Secondary Categories - 'Tooling' is spelled incorrectly

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#244]
The 'Tooling' option is spelled as 'Tooliing' in the options list at /wi/session/submit/details. Screenshot attached.

<img width="210" alt="Screen Shot 2020-01-07 at 7 52 34 PM" src="https://user-images.githubusercontent.com/5367626/71943755-44a17780-3187-11ea-826d-9f010e3b6287.png">

**Comment by saragibby** [comment]
@mcookWI looks like this got fixed up. Be great if you could review to make sure and then we can close this out.

**Comment by mcookWI** [comment]
Tooling is now spelled correctly.
