### ISSUE TITLE
/member/my-sessions - Should not allow for more than 3 sessions in 'Submitted' status

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#245]
We should not be allowing for more than 3 sessions to be in a 'Submitted' status. Currently, this is not the case. See attached.

<img width="981" alt="Screen Shot 2020-01-07 at 8 20 47 PM" src="https://user-images.githubusercontent.com/5367626/71945139-921fe380-318b-11ea-8a97-3ae1aac797d3.png">

**Comment by csell5** [comment]
This year we're going to let anyone submit as much as they want. Call it stress testing the system.
