### ISSUE TITLE
/member/my-sessions - Editing session in 'Withdrew' status and resubmitting does not change status

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#246]
Editing a withdrawn session and resubmitting it does not change the status to "Submitted" as it should.

Steps to create:

1. Go into /member/my-sessions and edit a session with the 'Withdrew' status. 
2. Go through screens and resubmit session.
3. System returns to the My Sessions screen and shows the submission still in the 'Withdrew' status.

See updated comment below ~If you refresh the page manually, it will then show the session in "Submitted" status.~

**Comment by mcookWI** [comment]
Update -- editing a Withdrew status session and clicking "Continue" does not change the status. Refreshing the page manually no longer updates the status. There does not appear to be a way to resubmit a withdrawn session or to delete it completely.

**Comment by saragibby** [comment]
Related to #280

**Comment by mcookWI** [comment]
You are now able to edit a session in 'Withdrew' status and resubmit. This will change to a 'Submitted' status.

However, if you are missing any required fields on the edit screen and click on 'Save', you will see the red error boxes as expected and will be unable to resubmit the session. The 'Save' button no longer functions after this and the user must manually go back to the 'My Sessions' page and edit the session again.
