### ISSUE TITLE
/member/create - Clicking 'Code of Conduct' or 'THAT Terms of Service' takes user out of creation process

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#248]
When a user clicks on either the 'Code of Conduct' or 'THAT Terms of Service' links on the Create Member Profile page, it takes them out of the creation path with no way to return. We need to make these links pop open another browser tab or window.

<img width="310" alt="Screen Shot 2020-01-07 at 8 56 44 PM" src="https://user-images.githubusercontent.com/5367626/71946712-3ad04200-3190-11ea-9959-4e25649954f7.png">

**Comment by brettski** [comment]
I cannot reproduce. @mcookWI please supply steps to reproduce this issue

**Comment by mcookWI** [comment]
1. Access the create a new user profile screen with a new account.
2. Click on the links for 'Code of Conduct' or 'THAT Terms of Service'. 

These both open in the same create window you were just in during step 1. From there, how do you go back to the creation screen you were just in? If you click Back in your browser, you get an error or blank screen. I am getting this in Safari, Firefox and Chrome for Mac.

**Comment by brettski** [comment]
This did not happen for me. The "Required fields" did trigger but I was able to complete the process without issue. 

This issue seems directly related to the other issue submitted, #239, which has a similar error, but references a text box, not a checkbox as that was the element interacted with. 

When the box was checked the following error shown in the browser console: 
```
Warning: A component is changing an uncontrolled input of type checkbox to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
    in input (created by Context.Consumer)
    in StyledComponent (created by FormInput__FormCheckbox)
    in FormInput__FormCheckbox (at FormInput.js:112)
    in label (created by Context.Consumer)
    in StyledComponent (created by FormLayout__FormLabel)
    in FormLayout__FormLabel (at FormInput.js:109)
    in FormInput (at ContactInfo.js:106)
    in div (created by Context.Consumer)
    in StyledComponent (created by ContactInfo__FlexFormRow)
    in ContactInfo__FlexFormRow (at ContactInfo.js:105)
    in ContactInfoForm (at create.js:241)
    in form (created by Form)
    in Form (at create.js:239)
    in Formik (at create.js:181)
    in div (created by Context.Consumer)
    in StyledComponent (created by ContentSection__ContainerInner)
    in ContentSection__ContainerInner (at ContentSection.js:56)
    in div (created by Context.Consumer)
    in StyledComponent (created by ContentSection__Container)
    in ContentSection__Container (at ContentSection.js:48)
    in ContentSection (at create.js:178)
    in div (at create.js:174)
    in createProfile (at _app.js:108)
    in div (created by Context.Consumer)
    in StyledComponent (created by Page__InnerPage)
    in Page__InnerPage (at Page.js:39)
    in div (created by Context.Consumer)
    in StyledComponent (created by Page__CorePage)
    in Page__CorePage (at Page.js:37)
    in div (created by Context.Consumer)
    in StyledComponent (created by Page__StyledPage)
    in Page__StyledPage (at Page.js:35)
    in ThemeProvider (at Page.js:32)
    in Page (created by ConnectFunction)
    in ConnectFunction (at _app.js:107)
    in ApolloProvider (at _app.js:106)
    in Provider (at _app.js:105)
    in MyApp (at withApolloClient.js:75)
    in withApollo(App) (created by withRedux(withApollo(App)))
    in withRedux(withApollo(App))
    in Container (created by AppContainer)
    in AppContainer
```

**Comment by mcookWI** [comment]
Are you clicking on the actual hyperlinks for those two items to bring them up? When you do, it loads another page in the same window as the profile creation page you were just on. I'm not talking about not checking the boxes and seeing an error message. This issue/request is to have the Code of Conduct and THAT Terms of Service  hyperlinks open in a new window/tab, so you aren't being pulled out of the profile creation process with no way to get back in.

**Comment by brettski** [comment]
Nope I certainly was NOT. So the links need to open to new windows. Got it. :)

**Comment by brettski** [comment]
Well simply adding `target='_blank'` didn't work. When the new page open is bombs on looking for bio. I guess the site thinks there should be a profile since we are "creating" one. This does beg the question, "Why are we grabbing full "me" information on each page load?

error:
![image](https://user-images.githubusercontent.com/473633/72009955-8a5c4f80-321c-11ea-9fa6-691a6313b6be.png)

**Comment by brettski** [comment]
This is now working as expected
