### ISSUE TITLE
'Meet the Speakers' button/link is hovering by itself 2/3 of the way down the main page

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#25]
There is a 'Meet the Speakers' button/link that is hovering on the bottom 1/3 of the page. Not sure where it should be, but it is out of place in the current location.

<img width="614" alt="Screen Shot 2019-10-26 at 11 58 41 PM" src="https://user-images.githubusercontent.com/5367626/67629937-930fcd00-f84c-11e9-8028-8ab306b3120b.png">

**Comment by saragibby** [comment]
I believe this got fixed yesterday afternoon with a change that flexed the header bar of the section.
