### ISSUE TITLE
Sessions: Agendas provided only for workshops

### ISSUE THREAD

**Issue by astralbodies** [ThatConference/that-website#250]
It appears that the Agenda field is being asked for all session types but really it's only necessary for workshops. Hide the field for non-workshop sessions.

**Comment by brettski** [comment]
I will not be hidden, but not be required. It doesn't hurt to have on if it is available. Would you disagree?

**Comment by astralbodies** [comment]
@brettski Agenda is too heavy for a 60 minute session and doesn't warrant a separate field in my opinion.

**Comment by brettski** [comment]
Okay. Though not a blocker for launch, we tie into this: #230 with it

**Comment by saragibby** [comment]
@astralbodies this was flipped to require agenda for regular sessions and not for workshops. I got this fixed up yesterday, be great if you can review when you have a chance.

**Comment by astralbodies** [comment]
Thanks for fixing this! Tested on the production site, and it works.
