### ISSUE TITLE
Withdrawing a session redirects to the main page

### ISSUE THREAD

**Issue by astralbodies** [ThatConference/that-website#267]
/member/my-sessions

Clicking on Withdraw on a session withdraws without confirmation (issue already filed for this) and then redirects back to the main conference page instead of my sessions.

**Comment by saragibby** [comment]
@astralbodies this should be fixed now so that you return to /member/my-sessions, tagging you in to review when you can

**Comment by mcookWI** [comment]
Withdrawing from a session no longer takes you back to the main conference page and leaves you at the /member/my-sessions page.
