### ISSUE TITLE
Edit profile screen doesn't verify URLs

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#275]
## Issue
When logged in with a user who has a profile, while you edit that profile the URL's are not verified.

## Steps to reproduce
1. Login as a user with a profile
1. Go to the profile from dropdown
1. Click edit profile
1. Enter text into any URL field and it is accepted. 

## What should be experenced

1. When editing URLs, Only URLs should be able to be added to the url fields

**Comment by saragibby** [comment]
I believe this got corrected with the updated regex to validate.

**Comment by brettski** [comment]
Look good
