### ISSUE TITLE
Newly created session not showing in "My Sessions" list initially

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#276]
## Issue
I am logged in on "My Sessions page" which shows any sessions I may have created. After creating a new session, I am brought back to this page, though the new session isn't shown until the page is reloaded.

## Steps to reproduce

1. Log in as user who has submitted a session
1. Go to "My Sessions" page
1. review list of "submitted and drafted sessions"
1. Click "Create New Session" Button
1. Run through and create a new session
1. After you submit the new session you are brought back to the My Sessions page

## What you see

The list of session is the same as before the new session was created

## What you should see

A list of all your sessions _including_ the one you just created.

**Comment by brettski** [comment]
FYI, this does work if it is your first session.

If when starting you have no sessions submitted. You go through the same process. When you get to My Sessions, the new session is displayed.

**Comment by brettski** [comment]
There still seems to be issues here.

**Comment by saragibby** [comment]
I'm looking at this now

**Comment by mcookWI** [comment]
@saragibby Has this been corrected? I submitted tests, and they are now showing up right away on the My Sessions page.

**Comment by saragibby** [comment]
Yes, I got this fixed with #322 and apparently super bad at updating github issues that there was a fix to be tested 🙃 

If you tested this and all is working, sounds like time to close it up.
