### ISSUE TITLE
Error when pressing continue prior to profile image upload

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#278]
If the continue button is pressed prior to the profile image being uploaded and error is thrown on the API and the page doesn't continue. 

This is not a blocker, but the user should not be able to continue until the page finishes its upload. 

There are no "loading" indicators to help the user know that we are waiting for the image to be uploaded.

**Comment by saragibby** [comment]
The update button (on edit) and continue button (on create) are disabled now while the image is uploading.

**Comment by brettski** [comment]
Corrected. Looks good.
