### ISSUE TITLE
Edit Session cannot move a session from draft to Submitted

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#280]
## Issue
A session in a user's list of session has a status of "Draft". Common for sessions which fell into an issue while being created. You may edit this session, though regardless of what information you fill out for the session, there is no way to "submit" it. It always remains in the "Draft" status.

**Comment by brettski** [comment]
Once a session is set to "withdrew" status, there is no way to get it out of this status.

**Comment by saragibby** [comment]
Duplicate of #246

**Comment by mcookWI** [comment]
You are now able to edit a session in 'Draft' status and click 'Save' to change it to Submitted. However, if there are any required fields missing data and you click on 'Save', you get the red errors, but are no longer able to submit the session. Clicking on the 'Save' button after this happens has no effect. The user needs to go back to the My Sessions Page and re-edit the session in 'Draft' status.

**Comment by brettski** [comment]
Issue successfully changing status

**Comment by mcookWI** [comment]
@brettski I will open another issue for the remaining item that I noted above. If you remove any data from a required field, you get an error message and can no longer submit the edited session.
