### ISSUE TITLE
"Step1_Temporary_Title" session being created when session abandoned on Session Details page

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#281]
A session with the title of "Step1_Temporary_Title" is being created and appears in the My Sessions page (/member/my-sessions) when a user abandons a session submission on the Session Details page.

If the user continues through at least the "Additional Info" page of the submission process and abandons, the session shows up in their listing with the Title they entered on the Session Details page.

If the user abandons their session submission before continuing through to at least the "Additional Info" page, we may want to consider deleting the request. Otherwise, the "Step1_Temporary_Title" session in their listing may cause confusion.

<img width="1007" alt="Screen Shot 2020-01-13 at 3 20 06 PM" src="https://user-images.githubusercontent.com/5367626/72294526-55386e80-361b-11ea-9fe5-3532bca83e0c.png">

The "Step1_Temporary_Title" was first noticed in a separate issue, https://github.com/ThatConference/that-website/issues/229 - please see additional notes there if needed.

**Comment by brettski** [comment]
Issue, #280 is related/may have a dependency on, as where sessions in "Draft" state cannot be promoted out of that state. so if a session gets in this state it will always be that way.

**Comment by saragibby** [comment]
@mcookWI this is updated now to no longer set that temporary title and the title got moved it to the first step of the session flow. Does that solve this particular issue?

**Comment by mcookWI** [comment]
This is good to go.
