### ISSUE TITLE
/member/<slug> social URLs are showing with /member/ in front of them

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#282]
The /member/<slug> page is showing the social URLs with /member/ in front of whatever the user puts in their profile. 

Example - facebook.com shows as /member/facebook.com, which does not exist. The social URLs should show as whatever the user has input on their profile.

<img width="201" alt="Screen Shot 2020-01-13 at 7 06 27 PM" src="https://user-images.githubusercontent.com/5367626/72304966-e1588f00-3637-11ea-95c0-a493b3cc71d8.png">

**Comment by saragibby** [comment]
@mcookWI do those circle buttons then link to say, /member/http://www.google.com?

**Comment by mcookWI** [comment]
This is no longer an issue in production. The links are now working as expected. I'm thinking this may have been some 'localhost' weirdness...
