### ISSUE TITLE
Contact Info - Phone Number Needs Supporting Formatting Hints in Error Msg

### ISSUE THREAD

**Issue by tsidel** [ThatConference/that-website#287]
## Issue
After you enter a phone number, the helper/placeholder text is no longer visible. If you weren't paying attention, it's not clear what the proper formatting is for a phone number

## Steps to reproduce
1. Begin filling out the contact info page, insert a phone number like (123)456-7890
2. You'll get an error message that reads "Phone number is not valid"

## What would be helpful to see
Helper text to accompany the error message that shows proper formatting for the phone number

<img width="366" alt="Screen Shot 2020-01-13 at 9 15 15 PM" src="https://user-images.githubusercontent.com/194128/72311346-ea525c00-3649-11ea-8d9e-b6243b27d3e8.png">

**Comment by woogychuck** [comment]
I was just looking at this same issue. Looking through the source, it appears that the regex in the validators requires the number start with a + followed by 2 or more numbers. This means that +56 is a valid phone number, but  603-555-1212, (603) 555-1212, and 6035551212 are not

I would happy to take a stab at fixing this, but I'd like some guidance on the solution.

I would like to update the validation to remove all non-number characters and ensure that the there are 7-14 numbers (which covers the range of international phone numbers based on some quick Googling).

Please feel free to assign this to me if that fix is good and I will tackle it ASAP!

**Comment by mcookWI** [comment]
Added help text below the Mobile Phone field on the Member Profile contact information screen.

'What would be helpful to see' is satisfied with this addition.

Closing this issue and will open another for future consideration of changing the regex validation.
