### ISSUE TITLE
Session Details - Supporting Links SVG too big for buttons

### ISSUE THREAD

**Issue by tsidel** [ThatConference/that-website#289]
## Issue
SVG Icons on Session Details submission page are not displaying properly

## Steps to Reproduce
Begin a session submission, at the bottom of the page near the "Supporting Links" is a "-" icon. After filling out the supporting links, a "+" icon appears.

## What you see
Oddly shaped/very large + & - icons

## What you should probably see
SVG Icons centered within the boxes/buttons with padding

<img width="1055" alt="Screen Shot 2020-01-13 at 9 29 57 PM" src="https://user-images.githubusercontent.com/194128/72311944-0fe06500-364c-11ea-8566-a93a094372db.png">

**Comment by saragibby** [comment]
@mcookWI @tsidel I took a stab at making these a bit more aligned. When you get a chance I would love some feedback on what you all think. Thanks!

**Comment by mcookWI** [comment]
The + button looks good, but the - looks like it's a little low in the box:

<img width="108" alt="Screen Shot 2020-01-16 at 6 40 36 PM" src="https://user-images.githubusercontent.com/5367626/72574763-d13aec80-388f-11ea-8fee-3d42b62c2bf5.png">

**Comment by tsidel** [comment]
@saragibby - I was able to look at this on production and it looks good to me.
