### ISSUE TITLE
"More About the counselor selection process" Inconsistent Capitalization

### ISSUE THREAD

**Issue by tparikka** [ThatConference/that-website#290]
![image](https://user-images.githubusercontent.com/7715790/72312140-baf11e80-364c-11ea-96b0-21eb9d94630c.png)

This button has inconsistent capitalization, as shown in the image above. It should be made consistent either by making only the first word capitalized or making the phrase fully capitalized.

**Comment by mcookWI** [comment]
Corrected in #295 - waiting for merge.

**Comment by mcookWI** [comment]
This has been corrected with #295 

<img width="320" alt="Screen Shot 2020-01-14 at 7 47 35 PM" src="https://user-images.githubusercontent.com/5367626/72397880-ca34a280-3706-11ea-89d9-b7d327c4e357.png">
