### ISSUE TITLE
Get FAQ page linked up in site

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#291]
An Counselor and perhaps an other FAQ are created but not linked anywhere in the site. Let's get them hooked up. 
in `markdown/faq.md`

**Comment by mcookWI** [comment]
Counselor FAQ is now available at https://www.thatconference.com/wi/counselor-submission-faq and is linked through https://www.thatconference.com/wi/counselor-start :

<img width="509" alt="Screen Shot 2020-02-08 at 4 06 24 PM" src="https://user-images.githubusercontent.com/5367626/74092683-17e5c600-4a8d-11ea-97e7-0154cca9291a.png">

The general FAQ has been updated with additional information at https://www.thatconference.com/wi/faq and is linked through the site page footer under "Resources":

<img width="98" alt="Screen Shot 2020-02-08 at 4 09 06 PM" src="https://user-images.githubusercontent.com/5367626/74092704-59767100-4a8d-11ea-8ed7-46947addf45a.png">
