### ISSUE TITLE
Member Profile: Profile Slug cannot be reused if user abandons creation process after Contact Info page

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#292]
If the user abandons the member profile creation process after going past the "Contact Info" page, the Profile Slug cannot be reused. When the user revisits the profile creation process, they are unable to reuse the Profile Slug they had entered before - they receive a 'Already Taken' error.

When the user revisits the process, we should be displaying the Profile Slug that they previously entered before the previous abandoned session.

Steps to reproduce:

1. Create a new users to thatconference.com
2. Enter "Contact Info" page data, including a Profile Slug
3. Click 'Continue' to move to the 'Online Presence' page
4. Close out of your browser
5. Revisit thatconference.com and login with the user created in Step 1. 
6. Click the "Complete Your Profile Today!" link in the header.
7. Enter 'Contact Info' like in Step 2, including the original Profile Slug.
8. Receive the 'Already Taken' error after entering the Profile Slug.

**Comment by saragibby** [comment]
@mcookWI can you take a look and see if this is still an issue after the changes we merged this morning?

**Comment by mcookWI** [comment]
If the user abandons the profile creation process after the Contact Info page, it is no longer saving off the Profile Slug they entered. They can then re-enter the Profile Slug they were using before abandoning the first time.
