### ISSUE TITLE
Persistent Horizontal Scroll in Chrome v79.0.3945.130

### ISSUE THREAD

**Issue by Ryanwiz** [ThatConference/that-website#308]
Seeing a horizontal scroll across many (all?) pages. 
Fixed with these css prop edits:
```
html {
    margin: 0;
    padding: 0;
    overflow-x: hidden;
}
.dFnDeq p {
    padding: 1rem 3rem;
}
.jmeYEX {
    right: 3rem;
}
```

**Comment by mcookWI** [comment]
This is being reported in Chrome (v79.0.3945.130).

**Comment by tsidel** [comment]
I went to work on this tonight, and I'm now unable to recreate it (except for the front page) in the same chrome version. @mcookWI & @Ryanwiz, do you still get the Persistent Horizontal Scroll in Chrome on other pages (beyond the front page)?

**Comment by mcookWI** [comment]
I am still seeing it on all pages in this Chrome version on Windows 10. This version on MacOS does not have the issue.

**Comment by Ryanwiz** [comment]
@tsidel Same on my end. Seeing it on all pages of this Chrome version using Windows 10.

**Comment by tsidel** [comment]
Thanks for the clarification! It was looking fine for me on a mac... I need to expand my testing options. Will look into this on Windows. Thanks!

**Comment by dstanich** [comment]
I'm on a Mac and see this on both Chrome (80.0.3987.132) and FF (73.0.1)
