### ISSUE TITLE
Overlapping mobile nav and sign-in link

### ISSUE THREAD

**Issue by tsidel** [ThatConference/that-website#310]
## Issue
On mobile devices and/or smaller screens, the mobile nav overlaps the sign in link

## Steps to Reproduce
Visit any page from a mobile device, or make your desktop browser window narrower than 400px. 

## What you see
Once the window is narrower than 400px, the sign in link goes under the mobile nav on the top right of the window

## What you should probably see
There should be plenty of touch clearance for both the sign in link and the mobile nav. 

<img width="343" alt="Screen Shot 2020-01-20 at 8 34 02 PM" src="https://user-images.githubusercontent.com/194128/72770986-2135ee00-3bc5-11ea-85de-90ba0b41c421.png">

**Comment by saragibby** [comment]
Closing, fixed with #318
