### ISSUE TITLE
Console Error: /wi - 404 error when reaching login.js

### ISSUE THREAD

**Issue by tparikka** [ThatConference/that-website#315]
## Expected Behavior
The site should not try to load resources that do not exist.

## Current Behavior
The site encounters a 404 (in the browser console) when trying to reach faq.js: `_next/static/that-website%401.0.0-ed79e2/pages/wi/faq.js:1`

and login.js: `/_next/static/that-website%401.0.0-ed79e2/pages/api/login.js`

## Possible Solution
Correct the invalid link to the resource.

## Steps to Reproduce
1. Navigate to https://www.thatconference.com/wi in Chrome

## Other Notes
It is also possible to reproduce the login.js failure by navigating to the site in Edge.

**Comment by mcookWI** [comment]
@tparikka - You are seeing these errors in the console, correct?

**Comment by mcookWI** [comment]
The 404 error is no longer being thrown for faq.js. The login.js error still exists.

**Comment by mcookWI** [comment]
This error is no longer appearing in the console when going to https://www.thatconference.com/wi .
