### ISSUE TITLE
Blank screen in Safari for member/create page

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#320]
When navigating to https://www.thatconference.com/member/create using Safari with MacOS the page is blank. 

Steps to reproduce:
Do not be logged in
It's recommended to use a 'private' window

1. Using a MacOS computer open Safari
2. Navigate to https://www.thatconference.com/member/create

The screen will be white. The Tidio widget does show though.

**Comment by mcookWI** [comment]
In order to reproduce this error, you will need to:

1. Have never logged into the new THAT Conference site in Safari or 
2. Delete all cookies related to the thatconference.com website

You can also go to File/New Private Window to simulate this scenario.

**Comment by mcookWI** [comment]
FYI - this is not happening in Chrome or Firefox - including Private/Incognito windows.

**Comment by brandonmartinez** [comment]
Reproduction steps (in Safari, latest):

1. Home page
2. Become a Counselor
3. Become a Counselor
4. Get Started

Blank screen occurs. Having dev tools open, there's a next.js error (null issue)

**Comment by GeekOnCoffee** [comment]
Working for me on Version 13.0.4 (14608.4.9.1.4), Mac 10.14.6

**Comment by mcookWI** [comment]
This issue was corrected over the weekend. I have also confirmed that this is working in Safari version 13.0.4 (15608.4.9.1.3) on MacOS 10.15.2, following the steps noted above.
