### ISSUE TITLE
Partner social icons display improperly

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#339]
The icons used as links to partner's social links don't display well. Image taken on Mac running Brave, Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit). 

![image](https://user-images.githubusercontent.com/473633/73285033-0b26bf80-41bb-11ea-8c6e-edf5f711d26a.png)

**Comment by tsidel** [comment]
Is there a way to leverage the CSS that's in SocialLinks.js for the MainLogoSection.js? Or is it better to redefine the MainLogoSection.js svg css styles to match the same code that's in SocialLinks.js? (When I edit the CSS in inspector to match the SocialLinks CSS that fixes this issue) I can update MainLogoSection.js to match, but then we're just repeating the same code—not sure if that's best practice here. I'm still getting used to styled components and how it works.

**Comment by brettski** [comment]
Let's ask @saragibby. I'm over my head here.

**Comment by brettski** [comment]
@saragibby or @kburnell are you abele to chime in here?

**Comment by saragibby** [comment]
This page on the live site is still fairly in flight, the social icons are all fixed up with #345. That will change them to load using the social links we use everywhere else, so we can close this issue up as soon as that PR is merged.

**Comment by saragibby** [comment]
Completed in #345
