### ISSUE TITLE
Footer has "arrow" in text instead of a graphic

### ISSUE THREAD

**Issue by astralbodies** [ThatConference/that-website#34]
<img width="417" alt="2019-10-27_11-46-51" src="https://user-images.githubusercontent.com/373903/67638150-8b354480-f8af-11e9-8951-30a37112f3e7.png">

Browser: Safari 13 on macOS 10.15 (happens on Chrome & Firefox as well)

**Comment by saragibby** [comment]
Removed and deployed. 
![image](https://user-images.githubusercontent.com/82035/67642174-27267680-f8d7-11e9-8550-594b3822d62d.png)
