### ISSUE TITLE
Event media partner logos larger than design

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#347]
Looking at XD design docs it appears the site's parter logo's on the event's partner page (https://www.thatconference.com/wi/partners). The design shows six logos horizontally. 

Task is to reduce size of logo displayed and allow for more logos displayed horizontally. 

![image](https://user-images.githubusercontent.com/473633/73851439-16996c80-47f3-11ea-87a1-706625ca0713.png)

**Comment by saragibby** [comment]
The original designs were done to reflect a fairly large screen sizes. We had to make some adjustments for all the things to look better on smaller screen sizes. Be good before this is started to figure out the sizes we want for these.

**Comment by brettski** [comment]
Logos do see too big on the page though
