### ISSUE TITLE
Main landing page - Not sure what icon is under "Camper"

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#35]
There is an icon under "Camper" on the main landing page. Not quite sure what it is for.

<img width="614" alt="Screen Shot 2019-10-27 at 11 48 24 AM" src="https://user-images.githubusercontent.com/5367626/67638187-e2d3b000-f8af-11e9-838d-a530f1e0b2c8.png">

**Comment by saragibby** [comment]
These are quotes, but not working for the font the set in the style guide

**Comment by GregLevenhagen** [comment]
The base SVG viewBox needed to be updated. This might come up again, depending on how we use the SVG styled component. In that case, we should probably add the x and y to the props to allow setting outside of the svg styled component.

![Screen Shot 2019-10-30 at 1 47 20 PM](https://user-images.githubusercontent.com/1812357/67888841-d05dae80-fb1b-11e9-9af1-654e73daaacd.png)
