### ISSUE TITLE
Add space between title and paragraph on Become a Camp Partner page

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#37]
On https://www.thatconference.com/becomeAPartner, additional space needs to be added between the title and paragraph shown below:

<img width="696" alt="Screen Shot 2019-10-27 at 12 10 07 PM" src="https://user-images.githubusercontent.com/5367626/67638520-2a0f7000-f8b3-11e9-9d27-5cf4ea8a16f6.png">

**Comment by kburnell** [comment]
fixed

**Comment by mcookWI** [comment]
Space has been added.
