### ISSUE TITLE
Header's notification center's background link wrong color

### ISSUE THREAD

**Issue by csell5** [ThatConference/that-website#389]
the header's notification background is the wrong shade of blue.

![image](https://user-images.githubusercontent.com/772569/75400807-ec087400-58c5-11ea-9863-fdc4847b79f6.png)

**Comment by zaudtke** [comment]
@csell5 @saragibby PR Created

**Comment by zaudtke** [comment]
PR #399 closed per request to clean up PR that had too many commits due to a merge issue on my part.  New PR coming later today..

**Comment by zaudtke** [comment]
@csell5 Let's try this again

**Comment by saragibby** [comment]
Thanks @zaudtke for getting this fixed up! 🤜 🤛
