### ISSUE TITLE
Footer doesn't snap to the bottom of a short page

### ISSUE THREAD

**Issue by csell5** [ThatConference/that-website#390]
Browse to a short page like https://www.thatconference.com/error and the footer doesn't snap to the bottom of the page.

![image](https://user-images.githubusercontent.com/772569/75401033-8bc60200-58c6-11ea-92a7-c5f14cd8cced.png)

**Comment by parthjawale** [comment]
Hi!
Can you list the steps to recreate this problem?
As this is working fine on my MacOS Chrome.

**Comment by zaudtke** [comment]
I **think** I have a fix for this.  I can't get to error pages in local dev mode, but I did find a job posting page that exhibited similar traits.  I can't get this into a PR until the previous 1 is closed.  If I don't see it, feel free to tag me when the other one is done, so I can move this one forward.  @csell5 @saragibby

**Comment by zaudtke** [comment]
@csell5 @saragibby  PR #402 Submitted
