### ISSUE TITLE
Voting: Using Y/N hot keys prevents Organizer Feedback from being captured in the database

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#405]
Steps to re-create:

1. In Session Voting, bring up a session to vote on and enter text in the "Organizer Feedback" box.
2. Click somewhere outside of the "Organizer Feedback" text box on the page so the box is no longer active.
3. Use the Y or N hot keys to place a vote.
4. Review vote in Retool and you will see that the "Notes" field for that vote is blank.

<img width="1346" alt="Screen Shot 2020-03-02 at 6 16 01 PM" src="https://user-images.githubusercontent.com/5367626/75731011-1b4b2680-5cb4-11ea-9ed1-8ed0d45b7e6e.png">
<img width="1199" alt="Screen Shot 2020-03-02 at 6 26 18 PM" src="https://user-images.githubusercontent.com/5367626/75731014-1dad8080-5cb4-11ea-98c8-8ab4428d4699.png">

This was duplicated in Safari 13.0.5 and Chrome 80.0.3987.122 on MacOS 10.15.3.

**Comment by saragibby** [comment]
Fixed up in #407 which is now merged to feature branch

**Comment by mcookWI** [comment]
This is now working correctly.
