### ISSUE TITLE
Contact page is showing placeholder information

### ISSUE THREAD

**Issue by astralbodies** [ThatConference/that-website#41]
<img width="432" alt="2019-10-27_12-59-06" src="https://user-images.githubusercontent.com/373903/67639085-91302300-f8b9-11e9-8901-a736dd32fd0f.png">

URL: https://www.thatconference.com/contact

Title has it. Page is only currently linked in the mobile site.

**Comment by saragibby** [comment]
We yank this page out of the repo so users no longer hit it. We will build it back out fresh and new.
