### ISSUE TITLE
Gatsby Is a Key Takeaway From Every Session in THAT Voting 😎

### ISSUE THREAD

**Issue by joshpierce** [ThatConference/that-website#422]
![image](https://user-images.githubusercontent.com/8643537/76098805-c0555000-5f8f-11ea-830d-4ad6ed913796.png)
![image](https://user-images.githubusercontent.com/8643537/76098853-d6fba700-5f8f-11ea-8d4e-29efc533386d.png)

Was also on every session prior to these two (once I noticed the issue).

I mean, don't get me wrong, Gatsby is cool and all, but guessing this one is a bug :)

**Comment by mcookWI** [comment]
@joshpierce Can you tell me what browser/version and OS you are using?

**Comment by schwechel** [comment]
I've got the same issue on Chrome  79.0.3945.130 (Official Build) (64-bit)

**Comment by mcookWI** [comment]
Can you try doing a manual page refresh to see if that fixes it? The session will change, but the one that was up when you refreshed will come back in the cycle later on.

**Comment by korthjp17** [comment]
Same here - Chrome 80.0.3987.106 - OSX 10.14.6

**Comment by korthjp17** [comment]
Clearing my cache and manual page refresh did seem to help so far

**Comment by schwechel** [comment]
page refresh fixed it for me

**Comment by mcookWI** [comment]
Thanks for letting me know. We'll still need to research further...

**Comment by dstanich** [comment]
Happened to me on iOS using FF.

It seemed to happen once I hit the actual session about Gatsby that had it as the first bullet.  After that they all had it. Refreshing fixed it.

**Comment by mcookWI** [comment]
Fixed by #435.
