### ISSUE TITLE
Firefox: Session Voting Review has tiny up/down icons

### ISSUE THREAD

**Issue by dstanich** [ThatConference/that-website#423]
In Firefox (Mac 73.0.1), at larger browser widths the up/down vote icons on the session voting review are tiny/not visible.  Appears to be related to flexbox since playing with those properties makes them appear.

![image](https://user-images.githubusercontent.com/10579383/76103207-e8947d00-5f96-11ea-9b79-3fecc9b1378a.png)

**Comment by GeekOnCoffee** [comment]
Confirmed in Frefox (Mac 74.0b6)
