### ISSUE TITLE
LOG_ROCKET error when running locally

### ISSUE THREAD

**Issue by abea** [ThatConference/that-website#429]
I followed the README instructions for running locally. When running `now dev` I got an error:

```
> UPDATE AVAILABLE Run `npm i -g now@latest` to install Now CLI 17.0.4
> Changelog: https://github.com/zeit/now/releases/tag/now@17.0.4
> Now CLI 16.7.3 dev (beta) — https://zeit.co/feedback
> Error! Env var "LOG_ROCKET" is not defined in `.env` file
Read more: https://err.sh/now/missing-env-file
```

Is this another setting we should add to the .env file and the README instructions?

**Comment by zaudtke** [comment]
@abea Yes, LOG_ROCKET with no value needs to be added to the .env file as well as the .env.build file.  There is a PR now pending with updated instructions and a new copy of the env.sample file.
