### ISSUE TITLE
Home page timeline behind moose

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#438]
On WI home page, https://www.thatconference.com/wi, in Timeline section the moose is covering part of the timeline (to the right). 
![image](https://user-images.githubusercontent.com/473633/76338145-4c37e680-62c6-11ea-979e-e461c750bbce.png)

**Comment by visshaljagtap** [comment]
@brettski I will work on to solve the issue

**Comment by brettski** [comment]
Thank you @visshaljagtap
