### ISSUE TITLE
No 'remote' indication on job listing detail page

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#441]
Job listings have a 'remote' switch. Jobs marked as remote show as such in the job listings list, but on in the detail page. 

Example job listings list: https://www.thatconference.com/partner/unspecified/jobs
See jobs, "Coffee Wizard" and "Director of Much Fun", they are both marked as remote. 

If you view either of these jobs, you'll notice that they aren't indicated as a 'remote' job.
Job listing detail pages:
https://www.thatconference.com/partner/unspecified/job/coffee-wizard
https://www.thatconference.com/partner/unspecified/job/director-of-much-fun

Add a item that the jobs are actually remote

**Comment by visshaljagtap** [comment]
@brettski ready to pick up this issue and will solve!

**Comment by visshaljagtap** [comment]
@brettski can you please close this issue, as it is solved!

**Comment by brettski** [comment]
Corrected with PR #447
