### ISSUE TITLE
Make it more apparent to scroll down on partner profile page

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#443]
When landing on a partner profile page (https://www.thatconference.com/partner/unspecified, https://www.thatconference.com/partner/THAT-Sample), it may not be apparent that the user can scroll down for more information. One partner has already commented on this. 

Please add an animation to the current down arrow or other indicator to let the user know to scroll down.

Example of current page on a smaller screen:
https://www.thatconference.com/partner/unspecified
![image](https://user-images.githubusercontent.com/473633/76536746-c002fc00-644a-11ea-8f0f-25398fb5b735.png)

**Comment by visshaljagtap** [comment]
Working on this!

**Comment by jonathanurias96** [comment]
Is this issue being handled?

**Comment by brettski** [comment]
Hi @jonathanurias96 it has not.

**Comment by jonathanurias96** [comment]
Can this issue be resolved by adding a functionality that when the icon gets clicked it scrolls you down?

**Comment by jonathanurias96** [comment]
Well anyway I can work on it, I will find a way that lets people know they can scroll down.

**Comment by jonathanurias96** [comment]
Check this pull request #518 I believe this can solve the issue
