### ISSUE TITLE
Partner logo not displayed correctly on /wi/jobs page

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#448]
On the jobs listing page, https://www.thatconference.com/wi/jobs, the partner logos are allowed to display too large. 

Task is to correct layout. 

Example:
![image](https://user-images.githubusercontent.com/473633/76875816-12735c80-683f-11ea-9e85-cae3ab25dc03.png)

**Comment by saragibby** [comment]
already working on this one

**Comment by saragibby** [comment]
Closing as this has been fixed.
