### ISSUE TITLE
No partner exists page missing header

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#450]
When landing on a link for a partner profile page which doesn't exist, the page doesn't show the sites header. 

For example navigate to, https://www.thatconference.com/partner/NoExist, you will notice that the header is missing. 
![image](https://user-images.githubusercontent.com/473633/76877493-7bf46a80-6841-11ea-8084-97d3d6f9d7fc.png)

**Comment by zaudtke** [comment]
@brettski I'm 98% sure I found the problem.  I just don't know how to fix it properly as there is a scooping issue around a variable that I think is needed to fix it.

1. [slug].js is the problem page
2. At the very bottom this line is the problem `PartnerDetail.headerType = 'layered';`
3. https://github.com/ThatConference/that-website/blob/master/pages/partner/%5Bslug%5D.js#L395
4. The function short circuits if a partner is not found and no hero section is added, but headerType is still set.  This causes all links to be white.

1 option that I don't think is right, is to add more components to CompanyNotFound to allow the image background.

The path I started down is to conditionally set `PartnerDetail.headerType`. The problem I ran into, is that line is outside the function and I wasn't sure if creating a variable outside the function to be set in onCompleted was the right approach.

Additional Note:  In Dev Mode, I can't get to the page to view if no partner, and running in prod mode locally isn't working for me.  I get errors about missing eventId.

Let me know if you need more details, or anything else for this.

**Comment by brettski** [comment]
Thank you @zaudtke! For dev mode to get the dynamic pages to work use `npm run dev` which will use next to run the site in development mode and not Zeit Now. There is a bug currently with Now cli v.16.

@saragibby Do you have an opinion on what what Al found here? A bit out of my depth.

**Comment by zaudtke** [comment]
@brettski @saragibby Here is a potential fix for this.  I reversed course and added the Hero Image, and some other things outlined in PR to make both scenarios work.
![Screen Shot 2020-06-07 at 1 49 56 PM](https://user-images.githubusercontent.com/1631560/83976400-aa756500-a8c7-11ea-8056-92261b1e16ce.png)

**Comment by brettski** [comment]
@saragibby or @kburnell are you able to review this PR please?

**Comment by brettski** [comment]
Thank you Al!
