### ISSUE TITLE
"Join Our Community" is on top of page footer

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#46]
The "Join Our Community" box is covering the "All Rights Reserved" footer.

See attached.

<img width="587" alt="Screen Shot 2019-10-27 at 2 08 17 PM" src="https://user-images.githubusercontent.com/5367626/67639891-7bbff680-f8c3-11e9-8286-dcb5ba843bb1.png">

**Comment by saragibby** [comment]
Fixed, but leaving issue open as the join newsletter box should be right aligned:
![image](https://user-images.githubusercontent.com/82035/67642190-46bd9f00-f8d7-11e9-88df-710a8b8d9fad.png)
