### ISSUE TITLE
Add search to All Partners page

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#467]
There is no existing way to search for partners on the all partners page. Even a browser find doesn't work. 

A react filter may do the trick to show matching partners to what is typed in a search box. 
Page: https://www.thatconference.com/partners

**Comment by GeekOnCoffee** [comment]
Is there a design for this?

**Comment by brettski** [comment]
Hi @GeekOnCoffee , no a design wasn’t made. 
My thought was a standard search box which used react to filter down the partners on the page. Note, I am not a front end developer, nor have I played one on tv. So I don’t know what would be best practice here and if reducing the tact list of elements is better than api calls. Though it sure sounds better in my head.

**Comment by brettski** [comment]
Currently the list of partners is not paged

**Comment by GeekOnCoffee** [comment]
@brettski makes sense, should be easy enough

**Comment by saragibby** [comment]
Sounds like to to do here is to add a search box at the top of the partners page?
What fields/data will that search through? 
Is the plan still to search on the front end after we fetch all partners?

**Comment by brettski** [comment]
> Sounds like to to do here is to add a search box at the top of the partners page?
That's correct, though you know how well I UI.

> What fields/data will that search through?
Company Name. I don't recall what else is available on the page

> Is the plan still to search on the front end after we fetch all partners?
correct

**Comment by saragibby** [comment]
Ok, got it. Wasn't sure if we also wanted to search keywords, location, jobs, etc. Just searching through name is straight forward to get in place.

**Comment by saragibby** [comment]
note: chatted with @GeekOnCoffee on progress, he's going to tag me in since I have some available bandwidth
