### ISSUE TITLE
Add contributor guidelines and update README

### ISSUE THREAD

**Issue by astralbodies** [ThatConference/that-website#48]
We're actively asking for outside contributors for this project, let's make sure we set them up to succeed. Add a contributor's guide and update the README to reflect the proper way to get them up and running on their local machine.

**Comment by saragibby** [comment]
@astralbodies I can add to this the general approach we are using as far as code structure + architecture.

**Comment by mcookWI** [comment]
@saragibby @astralbodies I recall seeing an updated README somewhere - have the guidelines been done as well? If so, should we close this out?
