### ISSUE TITLE
Add client side validation for member slug

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#510]
When members initially create their profile they are able to choose a slug the want to use for their account. Currently only validate check is one on the api. It would be useful and a better experience for the user if there was a client side check as well.

Member slugs have the following whitelist (RegExp): `/^[a-zA-Z0-9-_]+$/g` 
Allowed are, letters, numbers, underscore and dash only. 

The task here is to add a client-side check to notify user that they have entered an invalid slug. 

![image](https://user-images.githubusercontent.com/473633/84208508-80fc3b00-aa79-11ea-9931-8b9d0c05d08e.png)

**Comment by jonathanurias96** [comment]
Hi brettski I would like to take this issue

**Comment by brettski** [comment]
Sounds fantastic!  Thank you, we appreciate the help!

**Comment by jonathanurias96** [comment]
Hi brettski,
**Problem**
I am having a request error when I try to enter into the login page in the site locally.
<img width="916" alt="Screen Shot 2020-06-10 at 4 17 48 PM" src="https://user-images.githubusercontent.com/57416786/84328803-e1ea4880-ab37-11ea-8b55-3fa7a4b7cee7.png">

**Question**
Is there a way I can solve this?

**Things to know**
- I followed all the steps from the "5. Setting up your environment" and "5b. Vercel/Zeit linked project setup"
- Also I used the command `now dev` to run the project.

**Comment by brettski** [comment]
Yeah that’s an open issue we have. You are unable to access the auth server and we don’t have a way to do that for external devs at this time. We can’t expose our keys. Etc. We have not had the time to put together a solution for this. There are many pieces involved. Sorry for the trouble. If you have ideas we’re all ears.

**Comment by jonathanurias96** [comment]
Got it, thanks. Im going to keep working in the validation issue.

**Comment by jonathanurias96** [comment]
Ready for review

**Comment by brettski** [comment]
Fixed in PR #514
