### ISSUE TITLE
iOS Safari & Chrome /wi/become-a-partner - text covers images

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#52]
When loading thatconference.com/become-a-partner on iOS (13.1.3) Safari or Chrome (78.0.3904.67), the page does not load correctly. Text is covering images, etc. See attached.

![IMG_3624](https://user-images.githubusercontent.com/5367626/67642577-0d872e00-f8db-11e9-8b0c-7d95ea85017b.jpeg)

iOS Safari version

**Comment by kburnell** [comment]
resolved

**Comment by mcookWI** [comment]
/become-a-partner is now saying "Page Not Found".
