### ISSUE TITLE
Update WI/2021 Milestone Dates

### ISSUE THREAD

**Issue by csell5** [ThatConference/that-website#523]
![image](https://user-images.githubusercontent.com/772569/84945781-4b74d480-b0ad-11ea-8d05-feb2f251292f.png)

**Comment by brettski** [comment]
Initial dates set on wi/2021


Milestone | Days Before Precon | Date | Day of week
-- | -- | -- | --
THAT Conference | -1 | 7/27/2021 | Tuesday
THAT Pre-Conference | 0 | 7/26/2021 | Monday
Ticket Sales Close | 3 | 7/23/2021 | Friday
Room Blocks Close | 28 | 6/28/2021 | Monday
Not Guarenteed Swag | 55 | 6/1/2021 | Tuesday
Camp Counselors Announced | 84 | 5/3/2021 | Monday
Room Blocks Open | 84 | 5/3/2021 | Monday
Session Voting Ends | 113 | 4/4/2021 | Sunday
Session Voting Starts | 133 | 3/15/2021 | Monday
Call for Camp Counselors Ends | 133 | 3/15/2021 | Monday
Call for Camp Counselors | 175 | 2/1/2021 | Monday
Tickets Go On Sale | 175 | 2/1/2021 | Monday
Call for Partners | 451 | 5/1/2020 | Friday



** super impressive, I pasted a table from google sheets and it put it in markdown format!! I'm impressed anyway :)
