### ISSUE TITLE
Root Page / link unfurls to the wrong info

### ISSUE THREAD

**Issue by csell5** [ThatConference/that-website#526]
Root page unfurl has the wrong SEO data and image.

![image](https://user-images.githubusercontent.com/772569/84949647-2a16e700-b0b3-11ea-89f6-2850334a026a.png)

**Comment by csell5** [comment]
@saragibby You know this part the best. What's the best path forward to fix that up?

**Comment by saragibby** [comment]
We have defaults we fall back if not set by a page. Those defaults are all set to be WI info. I know where to get this done at, I can pick it up.
