### ISSUE TITLE
Root page: THAT WI 2021 and THAT TX 2021 Call for Sponsors text needs updating

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#529]
The THAT WI 2021 and THAT TX 2021 Call for Sponsors text should be consistent on both boxes:

WI says ‘Call for Sponsors is now open’
TX says ‘Call for sponsors now open!’

Also - ‘sponsors’ should be changed to ‘Partners’

![28E04BC4-78CA-4F2C-8D02-CBE9FE404546](https://user-images.githubusercontent.com/5367626/84961946-2abb7780-b0cb-11ea-86ee-2089a241660d.jpeg)

**Comment by zaudtke** [comment]
@mcookWI  I started to take a look at this, and found that the text comes from the api in the query made in Events.js.  Text will have to be updated in the database.

**Comment by brettski** [comment]
This is complete
