### ISSUE TITLE
iOS Safari & Chrome /wi/become-a-partner - page scrolls horizontally

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#53]
When loading thatconference.com/become-a-partner on iOS (13.1.3) Safari or Chrome (78.0.3904.67), the page scrolls horizontally.

**Comment by saragibby** [comment]
@mcookWI looks like this might have gotten fixed from other updates and clean up with worked through. When you can, give it a go and let me know if you still see this.

**Comment by mcookWI** [comment]
Unfortunately, it is still scrolling horizontally.

**Comment by saragibby** [comment]
Ahh, I see it now. There is a particular range of screen size where it is happening. I'll get 'er fixed. Thanks @mcookWI!

**Comment by kburnell** [comment]
fixed

**Comment by mcookWI** [comment]
Page is no longer scrolling horizontally, but showing "Page Not Found" text and not "Become a Partner". Leaving open until I can verify that the Partner page loads correctly.

**Comment by mcookWI** [comment]
/wi/become-a-partner no longer scrolls horizontally in Safari or Chrome on iOS 13.
