### ISSUE TITLE
Move general (non-event specific) documents up to root level

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#532]
Currently many general documents sit at the old route /wi (which is now /wi/2021). These non-event specific documents should be moved to the root level.

- Code of Conduct
- Terms of Use
- Copyright
- Privacy
- Anti-Harassment

**Comment by saragibby** [comment]
Do we have wording in these pages that relates specifically to WI? If so, assuming those will be addressed separately?

**Comment by saragibby** [comment]
I don't think it is possible to be a `bug` and an `enhancement`. I would think of this as an enhancement as we are changing existing intended behavior of app.
