### ISSUE TITLE
Root page event card link not working

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#553]
**Describe the bug**
Links in event cards at the bottom do not work when clicked. You can right click and open in new tab, etc. but simply clicking the link doesn't take you anywhere. 

**To Reproduce**
1. go to https://www.thatconference.com
1. navigate to any of the current event cards (see visual aid)
1. click link "THAT Online Tickets Now Available" or "Call for sponsors is now open" or "Call for sponsors now open!"
1. Notice that clicking the link doesn't take you anywhere
1. Right click the link and open in new window, you navigate to the desired page

**Expected behavior**
Clicking the link should take you to that page.

![image](https://user-images.githubusercontent.com/473633/86035473-05e7ce00-ba02-11ea-8b50-6198b34f8116.png)

**Comment by saragibby** [comment]
The bottom box with the highlight text is linking to the event, opening within the same tab. Has this already been fixed?

**Comment by brettski** [comment]
All of that navigation is a disaster after the pivot to the events landing page and not always using the router to determine event slug to use, etc. It does seem like these links do work now.

**Comment by saragibby** [comment]
Assuming the routing is a series of separate work, can this issue be closed since it is working?

**Comment by brettski** [comment]
Agreed, it can be closed

**Comment by saragibby** [comment]
Closing as item has already been completed.
