### ISSUE TITLE
Profile states over 13 and should be 13 and over

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#569]
**Describe the bug**
According to [COPPA](https://www.ftc.gov/enforcement/rules/rulemaking-regulatory-reform-proceedings/childrens-online-privacy-protection-rule) children **under** the age of 13 are restricted from internet data collection, etc.

thatconference.com profile states `Over 13 years old` which is technically incorrect. 

The suggested correction here is to update the site to reflect that a member must be 13 or more years old. 

The that-api-members also has the field isOver13, this will not change in the near future as it will disrupt many applications which relies on this data field. 

**To Reproduce**
1. login with user without a profile
1. proceed to create a profile
1. See field "Are you over 13 years old?"

Visual reference: 
![image](https://user-images.githubusercontent.com/473633/88076767-13dfc900-cb40-11ea-888b-85d7a9b1f3d8.png)

**Expected behavior**
Should read "Are >= 13 years old?"

**Additional context**
The entire site should be reviewed for where this text may be located. May not only be on profile create page.

**Comment by saragibby** [comment]
There is also some text in counselor submissions related to this: "My child is under 13 years of age, what should I do?"

What should that be updated to?

**Comment by brettski** [comment]
my child 13 years old or more
my child >= 13 (is how it is on that.us)
my child is under 13 is technically correct as the stipulation is 13 **and** older. 

I am not sure if this is helpful or not.

**Comment by saragibby** [comment]
So that particular FAQ item is correct as worded, so no changes needed?

**Comment by brettski** [comment]
Sorry, I don't know which FAQ item you are referring to. This issue is based on profile input form.

**Comment by saragibby** [comment]
It is an FAQ part of counselor submission (`counselor-submission-faq.md:16`).

**Comment by brettski** [comment]
The FAQ is correctly worded for the question and answer provided.
