### ISSUE TITLE
tickets.thatconference.com - Header ticket image references August 2020 Kalahari event

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#573]
**Describe the bug**
The header ticket image on tickets.thatconference.com references August 2020 Kalahari event.

**To Reproduce**
1. Go to tickets.thatconference.com
2. View header image (attached below)

**Expected behavior**
Ticket image needs to be updated to reference the August 3rd online event.

**Screenshots**

<img width="344" alt="Screen Shot 2020-07-27 at 6 30 14 PM" src="https://user-images.githubusercontent.com/5367626/88601896-3dfd2380-d037-11ea-81cc-2af1f652d2ad.png">

**Comment by brettski** [comment]
This will be updated for our next event. This is not relevant any longer for the Aug 2020 online event.
