### ISSUE TITLE
Members without photos associated with a partner show a missing/broken image

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#581]
**Describe the bug**
An a partner page, when an associated member of that partner doesn't have a profile photo their image is displayed broken/missing

**To Reproduce**
1. Go to: https://www.thatconference.com/partner/do-it-best-corp
1. Look at list of members in upper-right
1. See that **Aaron Diers** shows as a broken image

**Expected behavior**
For profiles without a photo the profile placeholder should be used

**Screenshots**
![image](https://user-images.githubusercontent.com/473633/88852836-72e2b500-d1b4-11ea-931a-61abb06cedc7.png)

**Comment by Chris-G-Dev** [comment]
Can I take this issue?

**Comment by saragibby** [comment]
@Chris-G-Dev I already got this completed, and am working on some refactoring before I open my PR.
