### ISSUE TITLE
ActiveCampaign Signup confirmation page has no return link

### ISSUE THREAD

**Issue by GeekOnCoffee** [ThatConference/that-website#61]
Ideally this should be styled, or at least have a "Back" link 

![Screen Shot 2019-10-29 at 10 49 28 AM](https://user-images.githubusercontent.com/240650/67784474-d713f500-fa39-11e9-9cfb-f83340d453a5.png)

**Comment by saragibby** [comment]
Welp, thats not good. Love that you created an issue @GeekOnCoffee! 🙌
