### ISSUE TITLE
Console error on loading root page (pr #630)

### ISSUE THREAD

**Issue by brettski** [ThatConference/that-website#631]
**Describe the bug**
For PR #630 
As the root page is loading the following error shows in conosle:
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

**To Reproduce**
1. Download branch and run with `vercel dev`
2. load root page at `http://localhost:3000`
3. open console, see error

**Device(s)/Browser(s) this is occurring on**
 - OS: OSx
 - Browser Brave with shields down
 - Version ?

**Comment by zaudtke** [comment]
Fix pushed to PR #630

**Comment by brettski** [comment]
LGTM
