### ISSUE TITLE
Page Header - "Call for Speakers..." background does not match rest of header

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that-website#67]
The background on the "Call for Speakers starts January 1st!" does not match the background of the rest of the header.

<img width="469" alt="Screen Shot 2019-10-31 at 7 46 20 AM" src="https://user-images.githubusercontent.com/5367626/67947968-b4f1b280-fbb2-11e9-9a17-496605d66401.png">

**Comment by saragibby** [comment]
Yup, it is a slightly darker color. It was intentionally designed that way to make it stand out a bit and give separation to text that will soon be added to the right of that box.
