### ISSUE TITLE
SVG Vector Image Issues IE11 At /wi, /wi/become-a-partner

### ISSUE THREAD

**Issue by tparikka** [ThatConference/that-website#70]
## Expected Behavior
SVG vector images should display correctly across all supported browsers (IE11 is still supported by Microsoft).

## Current Behavior
In IE11, the vectors do not render correctly:

![image](https://user-images.githubusercontent.com/7715790/67952201-ec645d00-fbba-11e9-83bb-944b96ceb62e.png)

![image](https://user-images.githubusercontent.com/7715790/67952223-f4240180-fbba-11e9-961c-4af664fdd625.png)

## Possible Solution
The SVGs may need to be adjusted to work on IE11, or a polyfill put in place to provide backstop support.

## Steps to Reproduce

Navigate to https://www.thatconference.com/wi in IE11 on Windows 10. This also applies to /wi/become-a-partner, where additionally it generates a horizontal scroll bar.

**Comment by saragibby** [comment]
@tparikka when you have a few minutes it would be great if you could checkout the social icons on the site in IE11 on Windows 10 and confirm they now display properly. @tsidel did an awesome job spotting the width was not set and got that fixed. Having you take a look now would be super helpful. Thanks!

**Comment by tparikka** [comment]
Looks good to me in IE11, Edge on Win10 Pro.
