### ISSUE TITLE
Homepage testimonial section is not stacking on mobile

### ISSUE THREAD

**Issue by saragibby** [ThatConference/that-website#82]
Here is the current view:=
![image](https://user-images.githubusercontent.com/82035/68259006-2dff6880-fffe-11e9-904d-9b20089cf873.png)

Needs to stack and size to mobile. Here is the design mock:
![image](https://user-images.githubusercontent.com/82035/68259028-48394680-fffe-11e9-9ed6-3fc66c361459.png)

**Comment by GeekOnCoffee** [comment]
Working on this

**Comment by saragibby** [comment]
@GeekOnCoffee here is the desktop design for that section:
![image](https://user-images.githubusercontent.com/82035/68550573-f57ed680-03d1-11ea-8f06-b7bd54c979bd.png)
